name: Publish Docker Image
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: docker/login-action@v1
        with: # Set the secret as an input
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: |
            docker.pkg.github.com/masa06033/ubuntu_1:0.0.5
